name: Format Libraries

on:
    push:
        branches:
            - "main"
            - "sg/automatic-formatting"
    workflow_dispatch:

jobs:
    check-message:
        runs-on: ubuntu-latest
        outputs: 
            continue: ${{ steps.check-message.continue }}
        steps:
            - name: Checkout Code
              id: checkout
              uses: actions/checkout@v4

            - name: Check Message
              id: check-message
              run: 
                echo Read Commit Message
                COMMIT_MESSAGE=$(git log -1 --pretty=%B)
                echo COMMIT_MESSAGE
                echo "continue=true" >> $GITHUB_OUTPUT
    get-modified-libraries:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              id: checkout
              uses: actions/checkout@v4

            - name: Format Libraries
              id: format-libraries
              run: |
                bash ./create_library_lists.sh

            # - name: Commit 
            #   id: commit
            #   run: |
            #     git status
            #     git add .
            #     git commit -m "chore: "